services:
  postgres:
    image: postgres:15
    container_name: ecommerce-postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ecommerce-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
